1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [1]:
import numpy as np

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])


array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [4]:
cov = np.mean(zp * ks) - np.mean(zp) * np.mean(ks)
cov

9157.839999999997

In [8]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [9]:
corr = cov/(zp.std()*ks.std())
corr

0.8874900920739158

In [10]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

2. Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [11]:
X = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

In [13]:
from statsmodels.stats.weightstats import _tconfint_generic as t_gen

In [14]:
mean_std_X = X.std(ddof=1) / (np.sqrt(len(X)))
t_gen(X.mean(), mean_std_X,len(X) - 1, 0.05, 'two-sided')

(110.55608365158724, 125.64391634841274)

3. Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [16]:
mean_std_X = np.sqrt(25) / np.sqrt(27)
t_gen(174.2, mean_std_X,27 - 1, 0.05, 'two-sided')

(172.2220658754539, 176.17793412454608)